package io.github.nicolaspurr.civicwallet.core.zk

import android.content.Context
import dagger.hilt.android.qualifiers.ApplicationContext
import org.json.JSONArray
import org.json.JSONObject
import java.io.FileNotFoundException
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Loads precomputed test vectors generated by `tools/generate_fixtures.mjs`.
 *
 * Fixtures reside in `assets/zk_fixtures/<key>.json` and contain only those parameters
 * that cannot be computed on-device without an in-app Poseidon hash implementation:
 * roots for both trees, authentication path elements, and the indexed sanctions tree low-leaf.
 * The account state tuple is also sourced directly from the fixture file, as it forms the
 * exact preimage for the committed tree leaf; divergence would produce an unsatisfiable witness.
 *
 * Parsing relies on the platform `org.json` implementation to avoid introducing external
 * serialization dependencies (e.g., kotlinx.serialization or Moshi) strictly for benchmarking
 * harness routines.
 */
@Singleton
class ZkFixtureLoader @Inject constructor(
    @ApplicationContext private val context: Context
) {

    private val cache = mutableMapOf<String, ZkFixture>()

    /**
     * Loads and caches the [ZkFixture] for a target [CircuitType], validating structural invariants.
     *
     * @throws FileNotFoundException if the fixture asset for the specified circuit variant
     *         has not been generated (e.g., generator script was omitted after modifying circuit targets).
     */
    @Synchronized
    fun load(type: CircuitType): ZkFixture = cache.getOrPut(type.key) {
        val path = "zk_fixtures/${type.key}.json"
        val raw = try {
            context.assets.open(path).bufferedReader().use { it.readText() }
        } catch (e: Exception) {
            throw FileNotFoundException(
                "Missing fixture '$path'. Run: node tools/generate_fixtures.mjs"
            )
        }
        parse(JSONObject(raw)).also { fixture ->
            require(fixture.circuit == type.key) {
                "Fixture file '$path' declares circuit '${fixture.circuit}'"
            }
            require(fixture.stateDepth == type.stateDepth) {
                "Fixture '$path' has stateDepth ${fixture.stateDepth}, " +
                        "circuit expects ${type.stateDepth}. Regenerate fixtures."
            }
            require(fixture.blacklistDepth == type.blacklistDepth) {
                "Fixture '$path' has blacklistDepth ${fixture.blacklistDepth}, " +
                        "circuit expects ${type.blacklistDepth}. Regenerate fixtures."
            }
        }
    }

    private fun parse(o: JSONObject) = ZkFixture(
        circuit = o.getString("circuit"),
        stateDepth = o.getInt("stateDepth"),
        blacklistDepth = o.getInt("blacklistDepth"),
        userPrivateKey = o.getString("userPrivateKey"),
        oldBalance = o.getLong("oldBalance"),
        oldSalt = o.getString("oldSalt"),
        oldDailySpent = o.getLong("oldDailySpent"),
        oldMonthlySpent = o.getLong("oldMonthlySpent"),
        oldEpochDay = o.getLong("oldEpochDay"),
        oldEpochMonth = o.getLong("oldEpochMonth"),
        stateRoot = o.getString("stateRoot"),
        statePathElements = o.getJSONArray("statePathElements").toStringList(),
        statePathIndices = o.getJSONArray("statePathIndices").toIntList(),
        blacklistRoot = o.optStringOrNull("blacklistRoot"),
        blLowValue = o.optStringOrNull("blLowValue"),
        blLowNextIndex = o.optStringOrNull("blLowNextIndex"),
        blLowNextValue = o.optStringOrNull("blLowNextValue"),
        blPathElements = o.optJSONArray("blPathElements")?.toStringList(),
        blPathIndices = o.optJSONArray("blPathIndices")?.toIntList()
    )

    private fun JSONArray.toStringList() = List(length()) { getString(it) }
    private fun JSONArray.toIntList() = List(length()) { getInt(it) }
    private fun JSONObject.optStringOrNull(k: String) = if (isNull(k)) null else optString(k)
}